import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import * as sass from 'sass'

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

/**
 * Compile styles/styles.scss to styles.css.
 *
 * Synchronous on purpose: the production build calls process.exit as soon as
 * the bundle is written, and an async compile could still be pending then,
 * which would ship a stale styles.css with no failure signal.
 */
function compileSCSS() {
	try {
		const result = sass.compile('styles/styles.scss');
		fs.writeFileSync('styles.css', result.css);
	} catch (error) {
		console.error(error);
		if (prod) {
			process.exit(1);
		}
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

compileSCSS();

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	// Watch the SCSS files for changes separately
	fs.watch('styles', { recursive: true }, (eventType, filename) => {
		if (eventType === 'change' && filename.endsWith('.scss')) {
			compileSCSS();
			console.log("Rebuilding styles.css")
		}
	});
}
