// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
import {closeMarker} from "./closeMarker"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&YQQOROOOcOSO'#C`OqORO'#CjO!VORO'#ChOOOP'#Cp'#CpQQOROOOOOP'#Cb'#CbO!hOSO,59UOOOP,58z,58zOOOP,59U,59UO!sOSO'#C`OOOP'#Cq'#CqO!{ORO'#CgOOOP'#Cm'#CmO#aORO'#CrO#uORO'#CfO#uORO'#CfO$WORO'#CtO$lORO'#CeO$lORO'#CeO$zOQO'#C_OOOP,58y,58yOOOP'#Cs'#CsO%VORO,59SOOOP,59S,59SOOOP-E6n-E6nOOOP,58|,58|OOOP1G.p1G.pO%hOSO'#CbOOOP-E6o-E6oOOOP,59^,59^OOOP-E6p-E6pO%mORO,59QOOOP,59`,59`OOOP-E6r-E6rOOOP,59P,59PO$lORO,59POOOP-E6q-E6qOOOP1G.n1G.nOOOP1G.k1G.k",
  stateData: "&O~OPSOTPO]RObSOjSO~OVVOWUO_XO`XO~OP]OTYO]ROb]Oc]OjZO~OPfOTPO]hObfOjfO~OWjO_kO`kO~OVlOWUO~OjZOPZXTZX]ZXbZXcZX~OjZOPfXTfX]fXbfXcfX~O]ROPYXTYXbYXcYX~O]ROjZOPhXThXbhXchX~OP]OTYOb]Oc]O~OTYO]ROjZO~OPfOTPO]vObfOjfO~OWjO~O]ROPYaTYabYacYa~O",
  goto: "$]iPPPjyP!WPP![!`!g!oP!{PP#TPP#_#e#n#z$QSSOTYaQbcdtTfRgWQORTgZdQbcdtTWPYTeQdScQdRqaU`QadRn^SSOT]^Q_`adpSSOTTfRgQXQSsbcRwtQTORiTW[Q^adRm[U_QadSo_pRp`QgRRugSbQdSrbtRtc",
  nodeNames: "⚠ RMarker TextColor Expression TcLeft LMarker Description Color InnerMarker TcRight Text Word CodeSection CODE Unfinished ColorEOF ColorWS REnd ENDLN EOF",
  maxTerm: 26,
  skippedNodes: [0],
  repeatNodeCount: 5,
  tokenData: "%U~RaXY!WYZ!]]^!Wpq!Wqr!Wrs!Ws#O!W#O#P!j#P#S!W#S#T$a#T#r!W#r#s$f#s;'S!W;'S;=`$y<%l~!W~O!W~~%P~!]Oj~~!bPj~YZ!e~!jOb~~!oYj~rs!W!P!Q!W#O#P!W#S#T!W#U#V!W#Y#Z!W#b#c!W#f#g!W#h#i!W#i#j#_~#bR!Q![#k!c!i#k#T#Z#k~#nR!Q![#w!c!i#w#T#Z#w~#zR!Q![$T!c!i$T#T#Z$T~$WR!Q![!W!c!i!W#T#Z!W~$fO]~~$kPj~!_!`$n~$qP#o#p$t~$yOT~~$|P;=`<%l!W~%UOc~",
  tokenizers: [closeMarker, 1, new LocalTokenGroup("!X~R[X^wpqw#q#r|#y#zw$f$gw#BY#BZw$IS$I_w$I|$JOw$JT$JUw$KV$KWw&FU&FVw~~!R~|O`~~!ROW~~!WO_~~", 54, 7)],
  topRules: {"TextColor":[0,2]},
  tokenPrec: 0
})
