import { parser } from 'src/parser/textColorLanguageParser';
import { LRLanguage } from '@codemirror/language';

/** The lezer grammar, wrapped for codemirror. Generated by `npm run grammar`. */
export const textColorLanguage = LRLanguage.define({
	name: 'textColorLanguage',
	parser: parser.configure({}),
});
